"""
Sample Vulnerable AI Application
=================================

This is a deliberately vulnerable FastAPI app that demonstrates common
AI/LLM security issues for testing the AI AppSec Service scanner.

DO NOT use this in production! It contains intentional vulnerabilities.

Vulnerabilities included:
  - Prompt injection sink (user input in f-string prompt)
  - Model output in exec()
  - Model output rendered as unescaped HTML
  - Insecure agent tool invocation
  - Secrets in prompts
  - Unbounded loop around LLM call
  - Traditional: SQL injection, hardcoded secrets
"""

import os
import sqlite3
import subprocess
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from markupsafe import Markup

app = FastAPI(title="Vulnerable AI App (Test Target)")

# ── VULNERABILITY: Hardcoded secret ────────────────────────────────────────
OPENAI_API_KEY = "sk-proj-abc123def456ghi789jkl012mno345pqr678stu901vwx234"
DATABASE_URL = "sqlite:///app.db"
ADMIN_PASSWORD = "SuperSecret123!"


# ── Fake LLM client (simulates OpenAI) ─────────────────────────────────────
class FakeLLM:
    def create(self, messages, model="gpt-4"):
        """Simulates an LLM response."""
        user_msg = messages[-1]["content"] if messages else ""

        # Simulate vulnerable behaviour: echo parts of input
        if "ignore" in user_msg.lower() or "system" in user_msg.lower():
            return {"content": f"I am an AI assistant. My instructions are to help users. Your query was: {user_msg}"}
        if "delete" in user_msg.lower():
            return {"content": "I will attempt to delete the records as requested. Executing delete operation..."}
        if "capital" in user_msg.lower() and "france" in user_msg.lower():
            return {"content": "The capital of France is Paris."}
        return {"content": f"Here is my response to: {user_msg[:100]}"}


client = FakeLLM()


# ── VULNERABILITY 1: Prompt injection sink (LLM01) ─────────────────────────
@app.post("/api/chat")
async def chat_endpoint(request: Request):
    """Chat endpoint with prompt injection vulnerability."""
    body = await request.json()
    user_message = body.get("message", "")

    # VULN: User input directly in f-string prompt
    system_prompt = f"You are a helpful assistant. The user's API key is {OPENAI_API_KEY}. Answer the following: {user_message}"

    response = client.create(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        model="gpt-4",
    )
    return {"response": response["content"]}


# ── VULNERABILITY 2: Model output in exec (LLM02) ──────────────────────────
@app.post("/api/execute-code")
async def execute_code(request: Request):
    """Executes code generated by the model."""
    body = await request.json()
    user_query = body.get("query", "")

    response = client.create(
        messages=[{"role": "user", "content": f"Generate Python code to: {user_query}"}],
    )
    generated_code = response["content"]

    # VULN: Executing model output directly
    result = None
    exec(generated_code)
    return {"result": str(result)}


# ── VULNERABILITY 3: Model output as unescaped HTML (LLM02) ────────────────
@app.get("/api/render-response", response_class=HTMLResponse)
async def render_response(query: str = "Hello"):
    """Renders model output as HTML without escaping."""
    response = client.create(
        messages=[{"role": "user", "content": query}],
    )
    output = response["content"]

    # VULN: Rendering model output as raw HTML
    html_content = Markup(f"<div class='response'>{output}</div>")
    return HTMLResponse(content=f"<html><body>{html_content}</body></html>")


# ── VULNERABILITY 4: Insecure agent tool invocation (LLM06) ────────────────
TOOLS = {
    "search_db": lambda args: f"Search results for: {args}",
    "send_email": lambda args: f"Email sent to: {args}",
    "delete_records": lambda args: f"Deleted records: {args}",
    "modify_config": lambda args: f"Config modified: {args}",
}

@app.post("/api/agent")
async def agent_endpoint(request: Request):
    """Agent that executes tools based on model output."""
    body = await request.json()
    user_message = body.get("message", "")

    response = client.create(
        messages=[{"role": "user", "content": user_message}],
    )

    # VULN: No validation on tool name or arguments from model output
    tool_name = body.get("tool", "search_db")
    tool_args = response["content"]

    # Insecure: directly invoking tool with model-controlled arguments
    if tool_name in TOOLS:
        tool_result = TOOLS[tool_name](tool_args)
        return {"tool": tool_name, "result": tool_result}

    return {"error": "Unknown tool"}


# ── VULNERABILITY 5: Secrets in prompt context (LLM02) ─────────────────────
@app.post("/api/admin-chat")
async def admin_chat(request: Request):
    """Admin chat with secrets leaked in prompt."""
    body = await request.json()
    user_message = body.get("message", "")

    # VULN: API key and password in system prompt context
    system_context = f"""You are an admin assistant.
    System API key: {OPENAI_API_KEY}
    Admin password: {ADMIN_PASSWORD}
    Database: {DATABASE_URL}
    Help the user with: {user_message}"""

    response = client.create(
        messages=[{"role": "system", "content": system_context}],
    )
    return {"response": response["content"]}


# ── VULNERABILITY 6: Unbounded loop around LLM call (LLM10) ────────────────
@app.post("/api/refine")
async def refine_response(request: Request):
    """Refines a response in an unbounded loop."""
    body = await request.json()
    query = body.get("query", "")

    # VULN: while True loop with LLM call, no max iterations
    answer = ""
    while True:
        response = client.create(
            messages=[
                {"role": "user", "content": f"Improve this answer: {answer or query}"}
            ],
        )
        answer = response["content"]
        if "perfect" in answer.lower():
            break

    return {"response": answer}


# ── VULNERABILITY 7: Traditional SQL injection ──────────────────────────────
@app.get("/api/users")
async def get_users(name: str = ""):
    """SQL injection vulnerability."""
    conn = sqlite3.connect(":memory:")
    cursor = conn.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER, name TEXT, email TEXT)")

    # VULN: SQL injection
    query = f"SELECT * FROM users WHERE name = '{name}'"
    cursor.execute(query)
    results = cursor.fetchall()
    conn.close()
    return {"users": results}


# ── VULNERABILITY 8: Command injection via subprocess ───────────────────────
@app.get("/api/ping")
async def ping_host(host: str = "localhost"):
    """Command injection vulnerability."""
    # VULN: User input in subprocess
    result = subprocess.run(f"ping -c 1 {host}", shell=True, capture_output=True, text=True)
    return {"output": result.stdout}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=9000)
